### PR TITLE
feat(android): initial Android version

### PR DESCRIPTION
**Pull request by m1ga**
This is just a very basic start!

FirebaseDatabase:
* getReference(); - path, url
* firebaseServerTimestamp

DatabaseReference:
* child() - idenfier, path/url
* childByAutoId()  - path
* setValue(Object), setValue(Object, Callback)
* removeValue
* goOffline
* goOnline
* event: value (e.key,e.value)
* updateChildValues
* setPriority(object, callback)
* keepSynced(boolean)

Firestore Databse:
* read data with `queryFirestore({collection, [document])`
* event: `query`

[firebase.database-android-1.0.0.zip](https://github.com/hansemannn/titanium-firebase-database/files/11231344/firebase.database-android-1.0.0.zip)

### CODE REVIEW

**Comment by m1ga** [comment]
able to push data with auto id now! Example works now on Android, although it complains on iOS that `FirebaseDatabase.getReference()` is not allowed without an argument.

Screenshot_20220217_125028

**Comment by hansemannn** [comment]
@m1ga iOS requires an object with at least one of these keys:
```
  NSString *identifier = [arguments objectForKey:@"identifier"];
  NSString *path = [arguments objectForKey:@"path"];
  NSString *url = [arguments objectForKey:@"url"];
  NSArray *observableEvents = [arguments objectForKey:@"observableEvents"];
```

**Comment by hansemannn** [comment]
Fixed as part of https://github.com/hansemannn/titanium-firebase-database/commit/3c98b589ddb099d070d0c8338b996bef13eb7469

**Comment by m1ga** [comment]
@hansemannn nice :+1: will test that later

**Comment by m1ga** [comment]
* setPriority
* keepSynced
* updateChildValues
* setValue(data, callback)

**Comment by hansemannn** [comment]
@m1ga Anything I should change / add on iOS as well?

**Comment by m1ga** [comment]
At the moment I try to match the iOS version. Still have to find my way around it to see what url/path does and where I need to store what :smile: 
It's working but I need to check if both plugins store it in the same places

**Comment by hansemannn** [comment]
@m1ga Is this ready for review? I am adding Firestore as well, so I found this one

**Comment by m1ga** [comment]
oh, have to test that again. It worked but I'm not sure if it stored the data the same way as iOS did.

**Comment by m1ga** [comment]
updated the library and fixed some issues I had with having new "child in child" items all the time.

Only did some smaller tests and the data is there
Screenshot_20220923_151721
I'm getting live updates/events and can add, update and delete items. 

So if you have some test case I would love to get some feedback if the structure is right at the end

**Comment by m1ga** [comment]
Since I had to use it with Firestore Database today:

```js
FirebaseDatabase.queryFirestore({
	collection: "collection",
	// document: "documentId"  // only one document - otherwise whole collection
});

FirebaseDatabase.addEventListener("query", function(e) {
	console.log(e.data);
});
```

will return an array of `id: "", data: "..."` where `data` is a JSON string.

[firebase.database-android-1.0.0.zip](https://github.com/hansemannn/titanium-firebase-database/files/11231336/firebase.database-android-1.0.0.zip)

no other options yet, but reading works. Keep it in this module (since it is just called database) or should we create a firestore-database spin-off?

**Comment by hansemannn** [comment]
Let's start with this one and iterate from there :)

**Pull request merged**
